/**
 * npm 版 NeteaseCloudMusicApi 端点清单（**自动生成，请勿手改**）
 *
 * 生成：`pnpm gen:netease-endpoints`
 * 来源：上游包 `module/*.js`（模块名 → 路径规则、首行注释 → 功能说明）
 * 共 377 个端点；用于 `@/api/netease` 通用调用器的类型安全路径与覆盖率校验。
 */

/** 端点信息 */
export interface NeteaseEndpoint {
  /** 模块名（与上游 `module/<name>.js` 一致） */
  name: string;
  /** 请求路径 */
  path: string;
  /** 功能说明 */
  desc: string;
}

/** 全部端点（按路径排序） */
export const NETEASE_ENDPOINTS = [
  { name: "activate_init_profile", path: "/activate/init/profile", desc: "初始化名字" },
  { name: "aidj_content_rcmd", path: "/aidj/content/rcmd", desc: "私人 DJ" },
  { name: "album", path: "/album", desc: "专辑内容" },
  { name: "album_detail", path: "/album/detail", desc: "数字专辑详情" },
  { name: "album_detail_dynamic", path: "/album/detail/dynamic", desc: "专辑动态信息" },
  { name: "album_list", path: "/album/list", desc: "数字专辑-新碟上架" },
  { name: "album_list_style", path: "/album/list/style", desc: "数字专辑-语种风格馆" },
  { name: "album_new", path: "/album/new", desc: "全部新碟" },
  { name: "album_newest", path: "/album/newest", desc: "最新专辑" },
  { name: "album_privilege", path: "/album/privilege", desc: "获取专辑歌曲的音质" },
  { name: "album_songsaleboard", path: "/album/songsaleboard", desc: "数字专辑&数字单曲-榜单" },
  { name: "album_sub", path: "/album/sub", desc: "收藏/取消收藏专辑" },
  { name: "album_sublist", path: "/album/sublist", desc: "已收藏专辑列表" },
  { name: "api", path: "/api", desc: "自定义请求（透传 uri/data 给上游接口，调试用）" },
  { name: "artist_album", path: "/artist/album", desc: "歌手专辑列表" },
  { name: "artist_desc", path: "/artist/desc", desc: "歌手介绍" },
  { name: "artist_detail", path: "/artist/detail", desc: "歌手详情" },
  { name: "artist_detail_dynamic", path: "/artist/detail/dynamic", desc: "歌手动态信息" },
  { name: "artist_fans", path: "/artist/fans", desc: "歌手粉丝" },
  { name: "artist_follow_count", path: "/artist/follow/count", desc: "歌手粉丝数量" },
  { name: "artist_list", path: "/artist/list", desc: "歌手分类" },
  { name: "artist_mv", path: "/artist/mv", desc: "歌手相关MV" },
  { name: "artist_new_mv", path: "/artist/new/mv", desc: "关注歌手新 MV" },
  { name: "artist_new_song", path: "/artist/new/song", desc: "关注歌手新歌" },
  { name: "artist_songs", path: "/artist/songs", desc: "歌手全部歌曲" },
  { name: "artist_sub", path: "/artist/sub", desc: "收藏与取消收藏歌手" },
  { name: "artist_sublist", path: "/artist/sublist", desc: "关注歌手列表" },
  { name: "artist_top_song", path: "/artist/top/song", desc: "歌手热门 50 首歌曲" },
  { name: "artist_video", path: "/artist/video", desc: "歌手相关视频" },
  { name: "artists", path: "/artists", desc: "歌手单曲" },
  { name: "audio_match", path: "/audio/match", desc: "听歌识曲（音频指纹匹配）" },
  { name: "avatar_upload", path: "/avatar/upload", desc: "更新头像" },
  { name: "banner", path: "/banner", desc: "首页轮播图" },
  { name: "batch", path: "/batch", desc: "批量请求接口" },
  {
    name: "broadcast_category_region_get",
    path: "/broadcast/category/region/get",
    desc: "广播电台 - 分类/地区信息",
  },
  {
    name: "broadcast_channel_collect_list",
    path: "/broadcast/channel/collect/list",
    desc: "广播电台 - 我的收藏",
  },
  {
    name: "broadcast_channel_currentinfo",
    path: "/broadcast/channel/currentinfo",
    desc: "广播电台 - 电台信息",
  },
  { name: "broadcast_channel_list", path: "/broadcast/channel/list", desc: "广播电台 - 全部电台" },
  { name: "broadcast_sub", path: "/broadcast/sub", desc: "广播电台 - 收藏/取消收藏电台" },
  { name: "calendar", path: "/calendar", desc: "音乐日历" },
  { name: "captcha_sent", path: "/captcha/sent", desc: "发送验证码" },
  { name: "captcha_verify", path: "/captcha/verify", desc: "校验验证码" },
  {
    name: "cellphone_existence_check",
    path: "/cellphone/existence/check",
    desc: "检测手机号码是否已注册",
  },
  { name: "chart_detail", path: "/chart/detail", desc: "获取指定维度音乐排行榜详情" },
  { name: "chart_song_detail", path: "/chart/song/detail", desc: "获取指定维度音乐排行榜列表" },
  { name: "check_music", path: "/check/music", desc: "歌曲可用性" },
  { name: "cloud", path: "/cloud", desc: "if (query.songFile.name.indexOf('flac') > -1) {" },
  { name: "cloud_import", path: "/cloud/import", desc: "云盘导入歌曲" },
  { name: "cloud_match", path: "/cloud/match", desc: "云盘歌曲信息匹配纠正" },
  { name: "cloudsearch", path: "/cloudsearch", desc: "搜索" },
  { name: "comment", path: "/comment", desc: "发送与删除评论" },
  { name: "comment_album", path: "/comment/album", desc: "专辑评论" },
  { name: "comment_dj", path: "/comment/dj", desc: "电台评论" },
  { name: "comment_event", path: "/comment/event", desc: "获取动态评论" },
  { name: "comment_floor", path: "/comment/floor", desc: "楼层评论" },
  { name: "comment_hot", path: "/comment/hot", desc: "热门评论" },
  { name: "comment_hug_list", path: "/comment/hug/list", desc: "评论抱一抱列表" },
  { name: "comment_like", path: "/comment/like", desc: "点赞与取消点赞评论" },
  { name: "comment_music", path: "/comment/music", desc: "歌曲评论" },
  { name: "comment_mv", path: "/comment/mv", desc: "MV评论" },
  { name: "comment_new", path: "/comment/new", desc: "评论" },
  { name: "comment_playlist", path: "/comment/playlist", desc: "歌单评论" },
  { name: "comment_video", path: "/comment/video", desc: "视频评论" },
  { name: "countries_code_list", path: "/countries/code/list", desc: "国家编码列表" },
  { name: "creator_authinfo_get", path: "/creator/authinfo/get", desc: "获取达人用户信息" },
  { name: "daily_signin", path: "/daily_signin", desc: "签到" },
  { name: "digitalAlbum_detail", path: "/digitalAlbum/detail", desc: "数字专辑详情" },
  { name: "digitalAlbum_ordering", path: "/digitalAlbum/ordering", desc: "购买数字专辑" },
  { name: "digitalAlbum_purchased", path: "/digitalAlbum/purchased", desc: "我的数字专辑" },
  { name: "digitalAlbum_sales", path: "/digitalAlbum/sales", desc: "数字专辑销量" },
  { name: "dj_banner", path: "/dj/banner", desc: "电台banner" },
  { name: "dj_category_excludehot", path: "/dj/category/excludehot", desc: "电台非热门类型" },
  { name: "dj_category_recommend", path: "/dj/category/recommend", desc: "电台推荐类型" },
  { name: "dj_catelist", path: "/dj/catelist", desc: "电台分类列表" },
  { name: "dj_detail", path: "/dj/detail", desc: "电台详情" },
  {
    name: "dj_difm_all_style_channel",
    path: "/dj/difm/all/style/channel",
    desc: "DIFM电台 - 分类",
  },
  {
    name: "dj_difm_channel_subscribe",
    path: "/dj/difm/channel/subscribe",
    desc: "DIFM电台 - 收藏频道",
  },
  {
    name: "dj_difm_channel_unsubscribe",
    path: "/dj/difm/channel/unsubscribe",
    desc: "DIFM电台 - 取消收藏频道",
  },
  {
    name: "dj_difm_playing_tracks_list",
    path: "/dj/difm/playing/tracks/list",
    desc: "DIFM电台 - 播放列表",
  },
  {
    name: "dj_difm_subscribe_channels_get",
    path: "/dj/difm/subscribe/channels/get",
    desc: "DIFM电台 - 收藏列表",
  },
  { name: "dj_hot", path: "/dj/hot", desc: "热门电台" },
  { name: "dj_paygift", path: "/dj/paygift", desc: "付费电台" },
  { name: "dj_personalize_recommend", path: "/dj/personalize/recommend", desc: "电台个性推荐" },
  { name: "dj_program", path: "/dj/program", desc: "电台节目列表" },
  { name: "dj_program_detail", path: "/dj/program/detail", desc: "电台节目详情" },
  { name: "dj_program_toplist", path: "/dj/program/toplist", desc: "电台节目榜" },
  { name: "dj_program_toplist_hours", path: "/dj/program/toplist/hours", desc: "电台24小时节目榜" },
  { name: "dj_radio_hot", path: "/dj/radio/hot", desc: "类别热门电台" },
  { name: "dj_recommend", path: "/dj/recommend", desc: "精选电台" },
  { name: "dj_recommend_type", path: "/dj/recommend/type", desc: "精选电台分类" },
  { name: "dj_sub", path: "/dj/sub", desc: "订阅与取消电台" },
  { name: "dj_sublist", path: "/dj/sublist", desc: "订阅电台列表" },
  { name: "dj_subscriber", path: "/dj/subscriber", desc: "电台详情" },
  { name: "dj_today_perfered", path: "/dj/today/perfered", desc: "电台今日优选" },
  { name: "dj_toplist", path: "/dj/toplist", desc: "新晋电台榜/热门电台榜" },
  { name: "dj_toplist_hours", path: "/dj/toplist/hours", desc: "电台24小时主播榜" },
  { name: "dj_toplist_newcomer", path: "/dj/toplist/newcomer", desc: "电台新人榜" },
  { name: "dj_toplist_pay", path: "/dj/toplist/pay", desc: "付费精品" },
  { name: "dj_toplist_popular", path: "/dj/toplist/popular", desc: "电台最热主播榜" },
  { name: "djRadio_top", path: "/djRadio/top", desc: "电台排行榜获取" },
  { name: "eapi_decrypt", path: "/eapi/decrypt", desc: "eapi 请求/响应解密（调试）" },
  { name: "event", path: "/event", desc: "获取动态列表" },
  { name: "event_del", path: "/event/del", desc: "删除动态" },
  { name: "event_forward", path: "/event/forward", desc: "转发动态" },
  {
    name: "fanscenter_basicinfo_age_get",
    path: "/fanscenter/basicinfo/age/get",
    desc: "粉丝年龄比例",
  },
  {
    name: "fanscenter_basicinfo_gender_get",
    path: "/fanscenter/basicinfo/gender/get",
    desc: "粉丝性别比例",
  },
  {
    name: "fanscenter_basicinfo_province_get",
    path: "/fanscenter/basicinfo/province/get",
    desc: "粉丝省份比例",
  },
  { name: "fanscenter_overview_get", path: "/fanscenter/overview/get", desc: "粉丝数量" },
  { name: "fanscenter_trend_list", path: "/fanscenter/trend/list", desc: "粉丝来源" },
  { name: "fm_trash", path: "/fm_trash", desc: "垃圾桶" },
  { name: "follow", path: "/follow", desc: "关注与取消关注用户" },
  { name: "get_userids", path: "/get/userids", desc: "根据昵称批量获取用户 id" },
  { name: "history_recommend_songs", path: "/history/recommend/songs", desc: "历史每日推荐歌曲" },
  {
    name: "history_recommend_songs_detail",
    path: "/history/recommend/songs/detail",
    desc: "历史每日推荐歌曲详情",
  },
  { name: "homepage_block_page", path: "/homepage/block/page", desc: "首页-发现 block page" },
  { name: "homepage_dragon_ball", path: "/homepage/dragon/ball", desc: "首页-发现 dragon ball" },
  { name: "hot_topic", path: "/hot/topic", desc: "热门话题" },
  { name: "hug_comment", path: "/hug/comment", desc: "抱一抱评论" },
  { name: "inner_version", path: "/inner/version", desc: "内部版本接口" },
  { name: "lbs_city_code", path: "/lbs/city/code", desc: "多级行政区划数据获取接口" },
  { name: "like", path: "/like", desc: "红心与取消红心歌曲" },
  { name: "likelist", path: "/likelist", desc: "喜欢的歌曲(无序)" },
  {
    name: "listen_data_realtime_report",
    path: "/listen/data/realtime/report",
    desc: "听歌足迹 - 本周/本月收听时长",
  },
  { name: "listen_data_report", path: "/listen/data/report", desc: "听歌足迹 - 周/月/年收听报告" },
  { name: "listen_data_today_song", path: "/listen/data/today/song", desc: "听歌足迹 - 今日收听" },
  { name: "listen_data_total", path: "/listen/data/total", desc: "听歌足迹 - 总收听时长" },
  {
    name: "listen_data_year_report",
    path: "/listen/data/year/report",
    desc: "听歌足迹 - 年度听歌足迹",
  },
  { name: "listentogether_accept", path: "/listentogether/accept", desc: "一起听 - 接受邀请" },
  { name: "listentogether_end", path: "/listentogether/end", desc: "一起听 结束房间" },
  { name: "listentogether_heatbeat", path: "/listentogether/heatbeat", desc: "一起听 发送心跳" },
  {
    name: "listentogether_play_command",
    path: "/listentogether/play/command",
    desc: "一起听 发送播放状态",
  },
  {
    name: "listentogether_room_check",
    path: "/listentogether/room/check",
    desc: "一起听 房间情况",
  },
  {
    name: "listentogether_room_create",
    path: "/listentogether/room/create",
    desc: "一起听创建房间",
  },
  { name: "listentogether_status", path: "/listentogether/status", desc: "一起听状态" },
  {
    name: "listentogether_sync_list_command",
    path: "/listentogether/sync/list/command",
    desc: "一起听 更新播放列表",
  },
  {
    name: "listentogether_sync_playlist_get",
    path: "/listentogether/sync/playlist/get",
    desc: "一起听 当前列表获取",
  },
  { name: "login", path: "/login", desc: "邮箱登录" },
  { name: "login_cellphone", path: "/login/cellphone", desc: "手机登录" },
  { name: "login_qr_check", path: "/login/qr/check", desc: "二维码登录 - 检查状态" },
  { name: "login_qr_create", path: "/login/qr/create", desc: "构建基础URL" },
  { name: "login_qr_key", path: "/login/qr/key", desc: "二维码登录 - 获取 key" },
  { name: "login_refresh", path: "/login/refresh", desc: "登录刷新" },
  { name: "login_status", path: "/login/status", desc: "登录状态" },
  { name: "logout", path: "/logout", desc: "退出登录" },
  { name: "lyric", path: "/lyric", desc: "歌词" },
  { name: "lyric_new", path: "/lyric/new", desc: "新版歌词 - 包含逐字歌词" },
  { name: "mlog_music_rcmd", path: "/mlog/music/rcmd", desc: "歌曲相关视频" },
  { name: "mlog_to_video", path: "/mlog/to/video", desc: "将mlog id转为video id" },
  { name: "mlog_url", path: "/mlog/url", desc: "mlog链接" },
  { name: "msg_comments", path: "/msg/comments", desc: "评论" },
  { name: "msg_forwards", path: "/msg/forwards", desc: "@我" },
  { name: "msg_notices", path: "/msg/notices", desc: "通知" },
  { name: "msg_private", path: "/msg/private", desc: "私信" },
  { name: "msg_private_history", path: "/msg/private/history", desc: "私信内容" },
  { name: "msg_recentcontact", path: "/msg/recentcontact", desc: "最近联系" },
  { name: "music_first_listen_info", path: "/music/first/listen/info", desc: "回忆坐标" },
  { name: "musician_cloudbean", path: "/musician/cloudbean", desc: "账号云豆数" },
  { name: "musician_cloudbean_obtain", path: "/musician/cloudbean/obtain", desc: "领取云豆" },
  { name: "musician_data_overview", path: "/musician/data/overview", desc: "音乐人数据概况" },
  { name: "musician_play_trend", path: "/musician/play/trend", desc: "音乐人歌曲播放趋势" },
  { name: "musician_sign", path: "/musician/sign", desc: "音乐人签到" },
  { name: "musician_tasks", path: "/musician/tasks", desc: "获取音乐人任务" },
  { name: "musician_tasks_new", path: "/musician/tasks/new", desc: "获取音乐人任务" },
  { name: "mv_all", path: "/mv/all", desc: "全部MV" },
  { name: "mv_detail", path: "/mv/detail", desc: "MV详情" },
  { name: "mv_detail_info", path: "/mv/detail/info", desc: "MV 点赞转发评论数数据" },
  { name: "mv_exclusive_rcmd", path: "/mv/exclusive/rcmd", desc: "网易出品" },
  { name: "mv_first", path: "/mv/first", desc: "最新MV" },
  { name: "mv_sub", path: "/mv/sub", desc: "收藏与取消收藏MV" },
  { name: "mv_sublist", path: "/mv/sublist", desc: "已收藏MV列表" },
  { name: "mv_url", path: "/mv/url", desc: "MV链接" },
  { name: "nickname_check", path: "/nickname/check", desc: "重复昵称检测" },
  { name: "personal_fm_mode", path: "/personal/fm/mode", desc: "私人FM - 模式选择" },
  { name: "personal_fm", path: "/personal_fm", desc: "私人FM" },
  { name: "personalized", path: "/personalized", desc: "推荐歌单" },
  { name: "personalized_djprogram", path: "/personalized/djprogram", desc: "推荐电台" },
  { name: "personalized_mv", path: "/personalized/mv", desc: "推荐MV" },
  { name: "personalized_newsong", path: "/personalized/newsong", desc: "推荐新歌" },
  { name: "personalized_privatecontent", path: "/personalized/privatecontent", desc: "独家放送" },
  {
    name: "personalized_privatecontent_list",
    path: "/personalized/privatecontent/list",
    desc: "独家放送列表",
  },
  { name: "pl_count", path: "/pl/count", desc: "私信和通知接口" },
  { name: "playlist_category_list", path: "/playlist/category/list", desc: "歌单分类列表" },
  { name: "playlist_catlist", path: "/playlist/catlist", desc: "全部歌单分类" },
  { name: "playlist_cover_update", path: "/playlist/cover/update", desc: "歌单封面上传" },
  { name: "playlist_create", path: "/playlist/create", desc: "创建歌单" },
  { name: "playlist_delete", path: "/playlist/delete", desc: "删除歌单" },
  { name: "playlist_desc_update", path: "/playlist/desc/update", desc: "更新歌单描述" },
  { name: "playlist_detail", path: "/playlist/detail", desc: "歌单详情" },
  { name: "playlist_detail_dynamic", path: "/playlist/detail/dynamic", desc: "歌单动态信息" },
  { name: "playlist_detail_rcmd_get", path: "/playlist/detail/rcmd/get", desc: "相关歌单推荐" },
  { name: "playlist_highquality_tags", path: "/playlist/highquality/tags", desc: "精品歌单 tags" },
  { name: "playlist_hot", path: "/playlist/hot", desc: "热门歌单分类" },
  {
    name: "playlist_import_name_task_create",
    path: "/playlist/import/name/task/create",
    desc: "歌单导入 - 元数据/文字/链接导入",
  },
  {
    name: "playlist_import_task_status",
    path: "/playlist/import/task/status",
    desc: "歌单导入 - 任务状态",
  },
  { name: "playlist_mylike", path: "/playlist/mylike", desc: "我喜欢的音乐（按时间）" },
  { name: "playlist_name_update", path: "/playlist/name/update", desc: "更新歌单名" },
  { name: "playlist_order_update", path: "/playlist/order/update", desc: "编辑歌单顺序" },
  { name: "playlist_privacy", path: "/playlist/privacy", desc: "公开隐私歌单" },
  { name: "playlist_subscribe", path: "/playlist/subscribe", desc: "收藏与取消收藏歌单" },
  { name: "playlist_subscribers", path: "/playlist/subscribers", desc: "歌单收藏者" },
  { name: "playlist_tags_update", path: "/playlist/tags/update", desc: "更新歌单标签" },
  { name: "playlist_track_add", path: "/playlist/track/add", desc: "收藏单曲到歌单" },
  {
    name: "playlist_track_all",
    path: "/playlist/track/all",
    desc: "通过传过来的歌单id拿到所有歌曲数据",
  },
  {
    name: "playlist_track_delete",
    path: "/playlist/track/delete",
    desc: "收藏单曲到歌单 从歌单删除歌曲",
  },
  { name: "playlist_tracks", path: "/playlist/tracks", desc: "收藏单曲到歌单 从歌单删除歌曲" },
  { name: "playlist_update", path: "/playlist/update", desc: "编辑歌单" },
  { name: "playlist_update_playcount", path: "/playlist/update/playcount", desc: "歌单打卡" },
  {
    name: "playlist_video_recent",
    path: "/playlist/video/recent",
    desc: "最近播放的视频（视频歌单）",
  },
  { name: "playmode_intelligence_list", path: "/playmode/intelligence/list", desc: "智能播放" },
  { name: "playmode_song_vector", path: "/playmode/song/vector", desc: "云随机播放" },
  { name: "program_recommend", path: "/program/recommend", desc: "推荐节目" },
  { name: "radio_sport_get", path: "/radio/sport/get", desc: "跑步漫游" },
  { name: "rebind", path: "/rebind", desc: "更换手机" },
  { name: "recent_listen_list", path: "/recent/listen/list", desc: "最近听歌列表" },
  { name: "recommend_resource", path: "/recommend/resource", desc: "每日推荐歌单" },
  { name: "recommend_songs", path: "/recommend/songs", desc: "每日推荐歌曲" },
  {
    name: "recommend_songs_dislike",
    path: "/recommend/songs/dislike",
    desc: "每日推荐歌曲-不感兴趣",
  },
  { name: "record_recent_album", path: "/record/recent/album", desc: "最近播放 - 专辑" },
  { name: "record_recent_dj", path: "/record/recent/dj", desc: "最近播放 - 播客" },
  { name: "record_recent_playlist", path: "/record/recent/playlist", desc: "最近播放 - 歌单" },
  { name: "record_recent_song", path: "/record/recent/song", desc: "最近播放 - 歌曲" },
  { name: "record_recent_video", path: "/record/recent/video", desc: "最近播放 - 视频" },
  { name: "record_recent_voice", path: "/record/recent/voice", desc: "最近播放 - 声音" },
  {
    name: "register_anonimous",
    path: "/register/anonimous",
    desc: "function getRandomFromList(list) {",
  },
  { name: "register_cellphone", path: "/register/cellphone", desc: "注册账号" },
  { name: "related_allvideo", path: "/related/allvideo", desc: "相关视频" },
  { name: "related_playlist", path: "/related/playlist", desc: "相关歌单" },
  { name: "resource_like", path: "/resource/like", desc: "点赞与取消点赞资源" },
  {
    name: "sati_resource_list",
    path: "/sati/resource/list",
    desc: "助眠解压 - 获取标签下资源列表",
  },
  {
    name: "sati_resource_list_more",
    path: "/sati/resource/list/more",
    desc: "助眠解压 - 查看同类推荐",
  },
  { name: "sati_resource_sub", path: "/sati/resource/sub", desc: "助眠解压 - 收藏" },
  { name: "sati_resource_sub_list", path: "/sati/resource/sub/list", desc: "助眠解压 - 收藏列表" },
  { name: "sati_tag_list", path: "/sati/tag/list", desc: "助眠解压 - 标签列表" },
  {
    name: "sati_timescene_resources_get",
    path: "/sati/timescene/resources/get",
    desc: "助眠解压 - 特定时间场景下的推荐资源",
  },
  { name: "scrobble", path: "/scrobble", desc: "听歌打卡" },
  { name: "search", path: "/search", desc: "搜索" },
  { name: "search_default", path: "/search/default", desc: "默认搜索关键词" },
  { name: "search_hot", path: "/search/hot", desc: "热门搜索" },
  { name: "search_hot_detail", path: "/search/hot/detail", desc: "热搜列表" },
  { name: "search_match", path: "/search/match", desc: "本地歌曲匹配音乐信息" },
  { name: "search_multimatch", path: "/search/multimatch", desc: "多类型搜索" },
  { name: "search_suggest", path: "/search/suggest", desc: "搜索建议" },
  { name: "send_album", path: "/send/album", desc: "私信专辑" },
  { name: "send_playlist", path: "/send/playlist", desc: "私信歌单" },
  { name: "send_song", path: "/send/song", desc: "私信歌曲" },
  { name: "send_text", path: "/send/text", desc: "私信" },
  { name: "setting", path: "/setting", desc: "设置" },
  { name: "share_resource", path: "/share/resource", desc: "分享歌曲到动态" },
  { name: "sheet_list", path: "/sheet/list", desc: "乐谱列表" },
  { name: "sheet_preview", path: "/sheet/preview", desc: "乐谱预览" },
  { name: "sign_happy_info", path: "/sign/happy/info", desc: "乐签信息" },
  { name: "signin_progress", path: "/signin/progress", desc: "签到进度" },
  { name: "simi_artist", path: "/simi/artist", desc: "相似歌手" },
  { name: "simi_mv", path: "/simi/mv", desc: "相似MV" },
  { name: "simi_playlist", path: "/simi/playlist", desc: "相似歌单" },
  { name: "simi_song", path: "/simi/song", desc: "相似歌曲" },
  { name: "simi_user", path: "/simi/user", desc: "相似用户" },
  { name: "song_chorus", path: "/song/chorus", desc: "副歌时间" },
  { name: "song_creators", path: "/song/creators", desc: "歌曲创作者信息" },
  { name: "song_detail", path: "/song/detail", desc: "歌曲详情" },
  { name: "song_downlist", path: "/song/downlist", desc: "会员下载歌曲记录" },
  { name: "song_download_url", path: "/song/download/url", desc: "获取客户端歌曲下载链接" },
  {
    name: "song_download_url_v1",
    path: "/song/download/url/v1",
    desc: "获取客户端歌曲下载链接 - v1",
  },
  { name: "song_dynamic_cover", path: "/song/dynamic/cover", desc: "歌曲动态封面" },
  { name: "song_like_check", path: "/song/like/check", desc: "歌曲是否喜爱" },
  { name: "song_lyrics_mark", path: "/song/lyrics/mark", desc: "歌词摘录 - 歌词摘录信息" },
  {
    name: "song_lyrics_mark_add",
    path: "/song/lyrics/mark/add",
    desc: "歌词摘录 - 添加/修改摘录歌词",
  },
  { name: "song_lyrics_mark_del", path: "/song/lyrics/mark/del", desc: "歌词摘录 - 删除摘录歌词" },
  {
    name: "song_lyrics_mark_user_page",
    path: "/song/lyrics/mark/user/page",
    desc: "歌词摘录 - 我的歌词本",
  },
  { name: "song_monthdownlist", path: "/song/monthdownlist", desc: "会员本月下载歌曲记录" },
  { name: "song_music_detail", path: "/song/music/detail", desc: "歌曲音质详情" },
  { name: "song_order_update", path: "/song/order/update", desc: "更新歌曲顺序" },
  { name: "song_purchased", path: "/song/purchased", desc: "已购单曲" },
  { name: "song_red_count", path: "/song/red/count", desc: "歌曲红心数量" },
  { name: "song_singledownlist", path: "/song/singledownlist", desc: "已购买单曲" },
  { name: "song_url", path: "/song/url", desc: "歌曲链接" },
  { name: "song_url_v1", path: "/song/url/v1", desc: "歌曲链接 - v1" },
  { name: "song_wiki_summary", path: "/song/wiki/summary", desc: "音乐百科基础信息" },
  {
    name: "starpick_comments_summary",
    path: "/starpick/comments/summary",
    desc: "云村星评馆 - 简要评论列表",
  },
  { name: "style_album", path: "/style/album", desc: "曲风-专辑" },
  { name: "style_artist", path: "/style/artist", desc: "曲风-歌手" },
  { name: "style_detail", path: "/style/detail", desc: "曲风详情" },
  { name: "style_list", path: "/style/list", desc: "曲风列表" },
  { name: "style_playlist", path: "/style/playlist", desc: "曲风-歌单" },
  { name: "style_preference", path: "/style/preference", desc: "曲风偏好" },
  { name: "style_song", path: "/style/song", desc: "曲风-歌曲" },
  { name: "summary_annual", path: "/summary/annual", desc: "年度听歌报告2017-2024" },
  { name: "threshold_detail_get", path: "/threshold/detail/get", desc: "获取达人达标信息" },
  { name: "top_album", path: "/top/album", desc: "新碟上架" },
  { name: "top_artists", path: "/top/artists", desc: "热门歌手" },
  { name: "top_list", path: "/top/list", desc: "排行榜" },
  { name: "top_mv", path: "/top/mv", desc: "MV排行榜" },
  { name: "top_playlist", path: "/top/playlist", desc: "分类歌单" },
  { name: "top_playlist_highquality", path: "/top/playlist/highquality", desc: "精品歌单" },
  { name: "top_song", path: "/top/song", desc: "新歌速递" },
  { name: "topic_detail", path: "/topic/detail", desc: "话题详情" },
  { name: "topic_detail_event_hot", path: "/topic/detail/event/hot", desc: "话题详情热门动态" },
  { name: "topic_sublist", path: "/topic/sublist", desc: "收藏的专栏" },
  { name: "toplist", path: "/toplist", desc: "所有榜单介绍" },
  { name: "toplist_artist", path: "/toplist/artist", desc: "歌手榜" },
  { name: "toplist_detail", path: "/toplist/detail", desc: "所有榜单内容摘要" },
  { name: "toplist_detail_v2", path: "/toplist/detail/v2", desc: "所有榜单内容摘要v2" },
  { name: "ugc_album_get", path: "/ugc/album/get", desc: "专辑简要百科信息" },
  { name: "ugc_artist_get", path: "/ugc/artist/get", desc: "歌手简要百科信息" },
  { name: "ugc_artist_search", path: "/ugc/artist/search", desc: "搜索歌手" },
  { name: "ugc_detail", path: "/ugc/detail", desc: "用户贡献内容" },
  { name: "ugc_mv_get", path: "/ugc/mv/get", desc: "mv简要百科信息" },
  { name: "ugc_song_get", path: "/ugc/song/get", desc: "歌曲简要百科信息" },
  { name: "ugc_user_devote", path: "/ugc/user/devote", desc: "用户贡献条目、积分、云贝数量" },
  { name: "user_account", path: "/user/account", desc: "账号信息" },
  { name: "user_audio", path: "/user/audio", desc: "用户创建的电台" },
  { name: "user_binding", path: "/user/binding", desc: "用户绑定信息" },
  { name: "user_bindingcellphone", path: "/user/bindingcellphone", desc: "绑定手机" },
  { name: "user_cloud", path: "/user/cloud", desc: "云盘数据" },
  { name: "user_cloud_del", path: "/user/cloud/del", desc: "云盘歌曲删除" },
  { name: "user_cloud_detail", path: "/user/cloud/detail", desc: "云盘数据详情" },
  { name: "user_comment_history", path: "/user/comment/history", desc: "用户历史评论" },
  { name: "user_detail", path: "/user/detail", desc: "用户详情" },
  { name: "user_detail_new", path: "/user/detail/new", desc: "用户详情" },
  { name: "user_dj", path: "/user/dj", desc: "用户电台节目" },
  { name: "user_event", path: "/user/event", desc: "用户动态" },
  { name: "user_follow_mixed", path: "/user/follow/mixed", desc: "当前账号关注的用户/歌手" },
  { name: "user_followeds", path: "/user/followeds", desc: "关注TA的人(粉丝)" },
  { name: "user_follows", path: "/user/follows", desc: "TA关注的人(关注)" },
  { name: "user_level", path: "/user/level", desc: "类别热门电台" },
  { name: "user_medal", path: "/user/medal", desc: "用户徽章" },
  { name: "user_mutualfollow_get", path: "/user/mutualfollow/get", desc: "用户是否互相关注" },
  { name: "user_playlist", path: "/user/playlist", desc: "用户歌单" },
  { name: "user_playlist_collect", path: "/user/playlist/collect", desc: "获取用户的收藏歌单列表" },
  { name: "user_playlist_create", path: "/user/playlist/create", desc: "获取用户的创建歌单列表" },
  { name: "user_record", path: "/user/record", desc: "听歌排行" },
  { name: "user_replacephone", path: "/user/replacephone", desc: "更换绑定手机" },
  { name: "user_social_status", path: "/user/social/status", desc: "用户状态" },
  { name: "user_social_status_edit", path: "/user/social/status/edit", desc: "用户状态 - 编辑" },
  {
    name: "user_social_status_rcmd",
    path: "/user/social/status/rcmd",
    desc: "用户状态 - 相同状态的用户",
  },
  {
    name: "user_social_status_support",
    path: "/user/social/status/support",
    desc: "用户状态 - 支持设置的状态",
  },
  { name: "user_subcount", path: "/user/subcount", desc: "收藏计数" },
  { name: "user_update", path: "/user/update", desc: "编辑用户信息" },
  { name: "verify_getQr", path: "/verify/getQr", desc: "验证接口 - 二维码生成" },
  { name: "verify_qrcodestatus", path: "/verify/qrcodestatus", desc: "验证接口 - 二维码检测" },
  { name: "video_category_list", path: "/video/category/list", desc: "视频分类列表" },
  { name: "video_detail", path: "/video/detail", desc: "视频详情" },
  { name: "video_detail_info", path: "/video/detail/info", desc: "视频点赞转发评论数数据" },
  { name: "video_group", path: "/video/group", desc: "视频标签/分类下的视频" },
  { name: "video_group_list", path: "/video/group/list", desc: "视频标签列表" },
  { name: "video_sub", path: "/video/sub", desc: "收藏与取消收藏视频" },
  { name: "video_timeline_all", path: "/video/timeline/all", desc: "全部视频列表" },
  { name: "video_timeline_recommend", path: "/video/timeline/recommend", desc: "推荐视频" },
  { name: "video_url", path: "/video/url", desc: "视频链接" },
  { name: "vip_growthpoint", path: "/vip/growthpoint", desc: "会员成长值" },
  { name: "vip_growthpoint_details", path: "/vip/growthpoint/details", desc: "会员成长值领取记录" },
  { name: "vip_growthpoint_get", path: "/vip/growthpoint/get", desc: "领取会员成长值" },
  { name: "vip_info", path: "/vip/info", desc: "获取 VIP 信息" },
  { name: "vip_info_v2", path: "/vip/info/v2", desc: "获取 VIP 信息" },
  { name: "vip_tasks", path: "/vip/tasks", desc: "会员任务" },
  { name: "vip_timemachine", path: "/vip/timemachine", desc: "黑胶时光机" },
  { name: "voice_delete", path: "/voice/delete", desc: "删除声音" },
  { name: "voice_detail", path: "/voice/detail", desc: "声音详情" },
  { name: "voice_lyric", path: "/voice/lyric", desc: "声音歌词" },
  {
    name: "voice_upload",
    path: "/voice/upload",
    desc: "格式:3b443c7c-a87f-468d-ba38-46d407aaf23a",
  },
  { name: "voicelist_detail", path: "/voicelist/detail", desc: "播客声音列表详情" },
  { name: "voicelist_list", path: "/voicelist/list", desc: "播客声音列表（按列表）" },
  { name: "voicelist_list_search", path: "/voicelist/list/search", desc: "声音搜索" },
  { name: "voicelist_search", path: "/voicelist/search", desc: "播客搜索" },
  { name: "voicelist_trans", path: "/voicelist/trans", desc: "播客声音列表（按电台/节目）" },
  { name: "weblog", path: "/weblog", desc: "操作记录" },
  { name: "yunbei", path: "/yunbei", desc: "/api/point/today/get" },
  { name: "yunbei_expense", path: "/yunbei/expense", desc: "云贝支出" },
  { name: "yunbei_info", path: "/yunbei/info", desc: "云贝账户信息" },
  { name: "yunbei_rcmd_song", path: "/yunbei/rcmd/song", desc: "云贝推歌" },
  { name: "yunbei_rcmd_song_history", path: "/yunbei/rcmd/song/history", desc: "云贝推歌历史记录" },
  { name: "yunbei_receipt", path: "/yunbei/receipt", desc: "云贝收入明细" },
  { name: "yunbei_sign", path: "/yunbei/sign", desc: "云贝签到" },
  { name: "yunbei_task_finish", path: "/yunbei/task/finish", desc: "云贝完成任务" },
  { name: "yunbei_tasks", path: "/yunbei/tasks", desc: "云贝所有任务" },
  { name: "yunbei_tasks_todo", path: "/yunbei/tasks/todo", desc: "云贝 todo 任务" },
  { name: "yunbei_today", path: "/yunbei/today", desc: "云贝今日签到信息" },
] as const satisfies readonly NeteaseEndpoint[];

/** 端点总数 */
export const NETEASE_ENDPOINT_COUNT = NETEASE_ENDPOINTS.length;

/** 端点路径（联合类型，供通用调用器约束参数） */
export type NeteaseEndpointPath = (typeof NETEASE_ENDPOINTS)[number]["path"];

/** 端点模块名 */
export type NeteaseEndpointName = (typeof NETEASE_ENDPOINTS)[number]["name"];

/** 模块名 → 路径 */
export const NETEASE_ENDPOINT_PATH_BY_NAME: Record<string, NeteaseEndpointPath> =
  Object.fromEntries(NETEASE_ENDPOINTS.map((item) => [item.name, item.path])) as Record<
    string,
    NeteaseEndpointPath
  >;

/** 路径 → 功能说明 */
export const NETEASE_ENDPOINT_DESC_BY_PATH: Record<string, string> = Object.fromEntries(
  NETEASE_ENDPOINTS.map((item) => [item.path, item.desc]),
);
